<?php

/**
 * @file
 * module file.
 */

/**
 * Implements hook_theme().
 */
function test_react_theme() {
  return [
    'hello_react_block' => [
      'variables' => [
        'content' => NULL
      ],
      'render element' => 'children',
    ],
    'icon3d_block' => [
      'variables' => [
        'content' => NULL
      ],
      'render element' => 'children',
    ],
    'cards_block' => [
      'variables' => [
        'content' => NULL
      ],
      'render element' => 'children',
    ],
  ];
}
